server:
  port: 9001
  
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf8&useSSL=false
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  
  rabbitmq:
    host: 127.0.0.1
    port: 5672

# eureka client
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
  instance:
    instance-id: tensquare-base           # 在eureka server中显示的实例名称
    prefer-ip-address: true               # 显示id
    
info:
  app.name: tensquare
  company.name: tensquare.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
