server:
  port: 7001

eureka:
  instance:
    hostname: eureka.com      # eureka服务的实例名称
  client:
    register-with-eureka: false   # false表示不向注册中心注册自己
    fetch-registry: false         # false表示自己就是注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   # euraka server交互的地址查询与注册服务
      # defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
