server:
  port: 9005
  
spring:
  application:
    name: tensquare-gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.254.128:3306/tensquare_gathering?characterEncoding=utf8&useSSL=false
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  
  rabbitmq:
    host: 192.168.254.128
    port: 5672
    
# eureka client
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
  instance:
    instance-id: tensquare-gathering      # 在eureka server中显示的实例名称
    prefer-ip-address: true               # 显示id
    
info:
  app.name: tensquare
  company.name: tensquare.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
