server:
  port: 9007
  
  tomcat:
    uri-encoding: UTF-8
  
spring:
  application:
    name: tensquare-search
    
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  http:
    encoding:
      charset: UTF-8
      force: true
      
  rabbitmq:
    host: 192.168.254.128
    port: 5672
      
# eureka client
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
  instance:
    instance-id: tensquare-search         # 在eureka server中显示的实例名称
    prefer-ip-address: true               # 显示id
    
info:
  app.name: tensquare
  company.name: tensquare.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
