server:
  port: 9006
  
spring:
  application:
    name: tensquare-spit
    
  data:
    mongodb:
      host: 127.0.0.1
      database: spitdb
      
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    timeout: 5000
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 0
        max-wait: -1
     
# eureka client
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
  instance:
    instance-id: tensquare-spit           # 在eureka server中显示的实例名称
    prefer-ip-address: true               # 显示id
    
info:
  app.name: tensquare
  company.name: tensquare.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$