server:
  port: 9008
  
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_user?characterEncoding=utf8&useSSL=false
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  redis:
    host: 192.168.254.128
    port: 6379
    database: 1
    timeout: 5000
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 0
        max-wait: -1
        
  rabbitmq:
    host: 192.168.254.128
    port: 5672
    
  devtools:
    restart:
      enabled: false

jwt:
  config:
    key: zhihao
    ttl: 7200000
    
# eureka client
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
  instance:
    instance-id: tensquare-user           # 在eureka server中显示的实例名称
    prefer-ip-address: true               # 显示id
    
info:
  app.name: tensquare
  company.name: tensquare.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
